"""Add profile_picture_url to users table

Revision ID: 59982310f822
Revises: 9dea21af7af2
Create Date: 2025-11-14 01:25:25.996672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59982310f822'
down_revision = '9dea21af7af2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_picture_url')

    # ### end Alembic commands ###
