"""add_video_url_and_workout_type_to_workout_sessions

Revision ID: a1b2c3d4e5f6
Revises: e1d0ef1201e0
Create Date: 2025-11-17 19:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'e1d0ef1201e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_type', sa.String(length=50), nullable=True, server_default='General'))
        batch_op.add_column(sa.Column('video_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.drop_column('video_url')
        batch_op.drop_column('workout_type')

    # ### end Alembic commands ###
